-- AlterTable
ALTER TABLE "BienImmobilier" ALTER COLUMN "statut" SET DEFAULT 'LIBRE';

-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "statut" SET DEFAULT 'EN_ATTENTE';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "role" SET DEFAULT 'CLIENT';
